language: go
go: "1.15.2"
os: linux

services:
  postgresql

before_script:
  - psql -c 'create database slash_test;' -U postgres
  - psql -d slash_test -c '\i scripts/init.sql;' -U postgres
  - psql -c "alter user postgres with password 'postgres';" -U postgres
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

jobs:
  include:
    - stage: build
      script: ./build/build.sh
    - stage: test
      script: ./build/test.sh
    - stage: lint
      script: golangci-lint run
