on:
  pull_request:
    branches:
      - master

name: build, test, lint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./build/build.sh

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: ./bin

  test:
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./build/test.sh

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: test_cov
          path: ./cover.out.tmp

  coverage:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: coverage
        uses: actions/download-artifact@v1
        with:
          name: test_cov

      - name: Check coverage
        run: ./build/coverage.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linters
        run: chmod 755 ./build/lint.sh
